
pipeline {
  agent any
  environment {
    RELEASE = '20.04'
  }
  stages {
    stage('Build') {
      agent any
      environment {
        LOG_LEVEL = 'INFO'
      }
      steps {
        echo "Building release for ${RELEASE} with log level ${LOG_LEVEL}"
      }
    }
    stage('Test') {
      steps {
        echo "Testing for release ${RELEASE}"
      }
    }
    stage('Deploy') {
      input {
        message 'Deploy?'
        ok 'DO it!'
        parameters {
          string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
        }
      }
      steps {
        echo "Deploying ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
      }
    }
  }
  post {
    always {
      echo 'Print every time.'
    }
  }
}
